# Generated by Django 4.0.5 on 2022-06-17 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_sensor_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
