# Generated by Django 4.0.5 on 2022-06-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['id']},
        ),
    ]
